language: objective-c
os: osx
osx_image: xcode9.3
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=RxSonosLib.xcworkspace
  - SCHEME=RxSonosLib
  matrix:
    - DESTINATION="OS=10.2,name=iPhone SE"
    - DESTINATION="OS=11.3,name=iPhone X"
before_install:
  - pod repo update > /dev/null
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME" | xcpretty
  - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty
